services:
  web:
    image: python:3.10
    container_name: django-app
    env_file:
      - .env
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/ecoursesv2
    working_dir: /ecoursesv2/ecoursesv2
    ports:
      - "10017:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres-db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: